name: Build Debian package for the pinenote-gnome-extension

permissions:
  contents: write

on:
  # manual triggering only
  workflow_dispatch:

jobs:
  create_debian_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: repo/

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install build-essential dpkg-dev debhelper-compat

    - name: Build package
      run: cd repo && dpkg-buildpackage -us -uc

    - name: ls
      run: ls

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pinenote-gnome-extension
        path: |
          pinenote-gnome-extension_*_all.deb
          pinenote-gnome-extension_*_amd64.buildinfo
          pinenote-gnome-extension_*_amd64.changes
          pinenote-gnome-extension_*.dsc
          pinenote-gnome-extension_*.tar.xz

  do_release:
    runs-on: ubuntu-latest
    needs:
      - create_debian_package
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Download image artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Make release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: draft_release
          draft: true
          files: |
            artifacts/pinenote-gnome-extension/pinenote-gnome-extension*
